# --- 语言字典 ---
MESSAGES = {
    "zh": {
        "title": "What To Gift",
        "caption": "送礼不用猜，AI 帮你选",
        "language_select": "Language / 语言",
        "select_relation": "对方是你的？",
        "select_budget": "预算范围",
        "input_occasion": "送礼场景？",
        "input_hobbies": "对方有什么爱好/特点？",
        "button_generate": "✨ 生成送礼方案",
        "placeholder_occasion": "生日",
        "placeholder_hobbies": "喜欢喝茶，对健康比较关注",
        "warning_hobbies": "请输入对方的爱好，让 AI 判断得更准！",
        "success_ai": "🎉 AI 已为您生成 3 个绝佳方案！",
        "reason": "💡 推荐理由：",
        "search_link": "🛒 立即搜索购买",
        "budget_options": ["200以内 (小心意)", "200 - 1000 (体面)", "1000 - 5000 (贵重)", "5000以上"],
        # ** FIX: 关系选项再次细化 **
        "relation_options": [
            "女朋友", 
            "老婆", 
            "男朋友", 
            "老公", 
            "父亲", 
            "母亲", 
            "爷爷", 
            "奶奶", 
            "好朋友 (男)", 
            "好朋友 (女)",
            "领导",
            "客户"
        ],
        "footer_ai": "由 Gemini AI 驱动，提供实时个性化推荐。",
        "footer_no_ai": "请配置您的 Gemini API Key 以解锁 AI 推荐功能。",
    },
    "en": {
        "title": "What To Gift",
        "caption": "No Idea? AI will pick one for you",
        "language_select": "Language / 语言",
        "select_relation": "Who is the recipient?",
        "select_budget": "Budget Range",
        "input_occasion": "Occasion?",
        "input_hobbies": "Recipient's hobbies/characteristics?",
        "button_generate": "✨ Generate Gift Ideas",
        "placeholder_occasion": "Birthday",
        "placeholder_hobbies": "Loves tea, interested in health and wellness",
        "warning_hobbies": "Please enter the recipient's hobbies for better AI suggestions!",
        "success_ai": "🎉 AI has generated 3 excellent ideas!",
        "reason": "💡 Recommendation Reason:",
        "search_link": "🛒 Search and Buy Now",
        "budget_options": ["Under ¥200 (Small Token)", "¥200 - ¥1000 (Decent)", "¥1000 - ¥5000 (Valuable)", "No limit"],
        # ** FIX: 关系选项再次细化 **
        "relation_options": [
            "Girlfriend", 
            "Wife", 
            "Boyfriend", 
            "Husband", 
            "Father", 
            "Mother", 
            "Grandfather", 
            "Grandmother", 
            "Close Friend (Male)", 
            "Close Friend (Female)",
            "Boss/Supervisor",
            "Client"
        ],
        "footer_ai": "Powered by Gemini AI, providing real-time personalized recommendations.",
        "footer_no_ai": "Please configure your Gemini API Key to unlock AI features.",
    }
}
